# Generated by Django 5.2.7 on 2025-11-11 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Nro. oficial del expediente o trámite', max_length=100, unique=True)),
                ('caratula_oficial', models.CharField(blank=True, help_text='Carátula oficial (Ej: PEREZ C/ GOMEZ S/ D Y P)', max_length=500, null=True)),
                ('organismo', models.CharField(blank=True, help_text='Ej: Juzgado Civil Nro 1, AFIP, Registro Civil', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_interno', models.CharField(help_text='Nombre descriptivo interno (Ej: Sucesión Pérez)', max_length=255)),
                ('naturaleza', models.CharField(choices=[('JUDICIAL', 'Judicial'), ('EXTRAJUDICIAL', 'Extrajudicial'), ('ADMINISTRATIVO', 'Administrativo')], default='JUDICIAL', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='clientes.cliente')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_responsable', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos', to='casos.expediente')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('COMPLETADO', 'Completado'), ('A_REVISAR', 'A revisar'), ('PENDIENTE', 'Pendiente'), ('ESPERANDO', 'Esperando')], default='PENDIENTE', max_length=20)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='casos.caso')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['fecha'],
            },
        ),
    ]
