# Generated by Django 5.2.7 on 2025-11-11 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente_SIPED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(help_text='Nro. oficial del expediente (Ej: 19827/2025)', max_length=100, unique=True)),
                ('link_detalle', models.URLField(blank=True, max_length=500, null=True)),
                ('caratula', models.CharField(blank=True, help_text='Carátula oficial (Ej: PEREZ C/ GOMEZ S/ D Y P)', max_length=500, null=True)),
                ('partes', models.IntegerField(blank=True, help_text="Campo 'partes' del CSV", null=True)),
                ('estado', models.CharField(blank=True, help_text='Ej: A DESPACHO, PUBLICADO', max_length=100, null=True)),
                ('fec_ult_mov', models.DateField(blank=True, null=True)),
                ('localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('dependencia', models.CharField(blank=True, help_text='Ej: Juzgado Civil Nro 1', max_length=255, null=True)),
                ('secretaria', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Expediente SIPED',
                'verbose_name_plural': 'Expedientes SIPED',
            },
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['-fecha_presentacion'], 'verbose_name': 'Movimiento SIPED', 'verbose_name_plural': 'Movimientos SIPED'},
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='caso',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='fecha',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_firma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_presentacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='generado_por',
            field=models.CharField(blank=True, help_text='Ej: JUZGADO, o nombre de abogado', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='link_escrito',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='nombre_escrito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(blank=True, help_text='Ej: ESCRITO, ESTESE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='descripcion',
            field=models.TextField(blank=True, help_text="Campo 'descripcion' del CSV", null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='estado',
            field=models.CharField(blank=True, help_text='Ej: PUBLICADO', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='expediente',
            field=models.ForeignKey(default=0.548641975308642, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='casos.expediente_siped'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caso',
            name='expediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos', to='casos.expediente_siped'),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('A_REVISAR', 'A revisar'), ('COMPLETADO', 'Completado')], default='PENDIENTE', help_text='Estado interno de la tarea', max_length=20)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='casos.caso')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea Interna',
                'verbose_name_plural': 'Tareas Internas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='Expediente',
        ),
    ]
